### ISSUE TITLE
Cannot download the model weight.

### ISSUE THREAD

**Issue by NorahGreen** [visresearch/patchmix#1]

**Comment by sccbhxc** [comment]
Can you provide more details, such as the seen link page? Maybe you need a proxy.

**Comment by NorahGreen** [comment]
I got the following message : 
![1687836216324_mosaic](https://github.com/visresearch/patchmix/assets/28557659/65abaad7-b685-4c59-81ae-ab0c18a38aaa)
I do not know how to solve this problem.

**Comment by NorahGreen** [comment]
I got the following message from the download link:
![1687836216324_mosaic (1)](https://github.com/visresearch/patchmix/assets/28557659/79ef1f11-fd15-4266-9433-81732ce90dae)
I do not know how to solve this problem.

**Comment by sccbhxc** [comment]
I will fix these links. You can obtain the trained weights from https://csueducn-my.sharepoint.com/:f:/g/personal/221258_csu_edu_cn/EsSud0DB_edBiODrZhDbNpsBwfTbpOkuJ_TKA6mTYSi6Dw

**Comment by NorahGreen** [comment]
Thank you for your help.
