### ISSUE TITLE
模型列表的含义

### ISSUE THREAD

**Issue by safehumeng** [visresearch/patchmix#2]
麻烦问下这些模型列表代表的是在这个数据集上不同方式的结果么，可以理解成要想使用必须在自己的数据集上进行训练么
![image](https://github.com/visresearch/patchmix/assets/16226299/e8b25bc3-9866-4fd8-b670-07757ee59721)

**Comment by sccbhxc** [comment]
这个表格的含义是，在对应数据集上用对应的evaluation protocol测出来的准确率，其中kNN Accuracy中对应的模型link，是pretrained model weights，你可以通过finetuning这个pretrained model来适配自己的数据集。

**Comment by safehumeng** [comment]
> 这个表格的含义是，在对应数据集上用对应的evaluation protocol测出来的准确率，其中kNN Accuracy中对应的模型link，是pretrained model weights，你可以通过finetuning这个pretrained model来适配自己的数据集。

好的，谢啦
