### ISSUE TITLE
hyperparameter for CIFAR100

### ISSUE THREAD

**Issue by Wu-Jian-Ting** [visresearch/patchmix#5]
Hello, I have used the source code for trainning CIFAR100, but the loss run down slowy, do anyone have hyperparameter for CIFAR100?

**Comment by sccbhxc** [comment]
All hyperparameters can be found at https://github.com/visresearch/patchmix/blob/main/config. 
I suggest that you can improve the running efficiency of the code according to your GPUs.
The contrastive loss descends fast at the initial stage and then slows down.
